# Basics of turtle graphics!!
import turtle
jane = turtle.Turtle()
jane.shape("turtle")
jane.width(5)
jane.color("green")
jane.speed(0)
jane.left(90)
jane.forward(100)
jane.left(30)
jane.forward(100)
jane.backward(100)
jane.right(60)
jane.forward(100)
jane.backward(100)
jane.left(30)
jane.backward(100)
